import type { Product, ProductImage, Specifications, Country, ShippingOption } from '../types';

function createImages(productId: string, name: string, nameAr: string, count: number): ProductImage[] {
  const images: ProductImage[] = [];
  for (let i = 1; i <= count; i++) {
    images.push({
      url: `https://via.placeholder.com/800x800?text=${encodeURIComponent(name)}`,
      alt: `${name} - Image ${i}`,
      altAr: `${nameAr} - الصورة ${i}`,
      width: 800,
      height: 800,
      isPrimary: i === 1,
    });
  }
  return images;
}

export const mockProducts: Product[] = [
  {
    id: 'tab-001',
    name: 'Apple iPad Pro 12.9-inch (M2, 2022)',
    nameAr: 'أبل آيباد برو 12.9 بوصة (M2، 2022)',
    description:
      'The ultimate iPad experience with the powerful M2 chip, stunning 12.9-inch Liquid Retina XDR display, and all-day battery life. Perfect for creative professionals and power users who demand the best.',
    descriptionAr:
      'تجربة آيباد المثالية مع شريحة M2 القوية وشاشة Liquid Retina XDR المذهلة بحجم 12.9 بوصة وعمر بطارية يدوم طوال اليوم. مثالي للمحترفين المبدعين والمستخدمين الذين يطلبون الأفضل.',
    brand: 'Apple',
    price: 8499,
    currency: 'SAR',
    images: createImages('tab-001', 'iPad Pro 12.9 M2', 'آيباد برو 12.9 M2', 3),
    specifications: {
      screenSize: '12.9"',
      resolution: '2732×2048',
      processor: 'Apple M2',
      ram: '16GB',
      storage: '512GB',
      battery: '40.88Wh',
      camera: '12MP Wide + 10MP Ultra Wide',
      weight: '682g',
      dimensions: '280.6×214.9×6.4mm',
      os: 'iPadOS 16',
    },
    availability: 'in_stock',
    stockQuantity: 15,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-002',
    name: 'Apple iPad Pro 11-inch (M2, 2022)',
    nameAr: 'أبل آيباد برو 11 بوصة (M2، 2022)',
    description:
      'Packed with the M2 chip and featuring a brilliant 11-inch Liquid Retina display. The perfect balance of power and portability for professionals on the go.',
    descriptionAr:
      'مزود بشريحة M2 ويتميز بشاشة Liquid Retina الرائعة بحجم 11 بوصة. التوازن المثالي بين القوة وقابلية النقل للمحترفين أثناء التنقل.',
    brand: 'Apple',
    price: 6799,
    currency: 'SAR',
    images: createImages('tab-002', 'iPad Pro 11 M2', 'آيباد برو 11 M2', 3),
    specifications: {
      screenSize: '11"',
      resolution: '2388×1668',
      processor: 'Apple M2',
      ram: '8GB',
      storage: '256GB',
      battery: '28.65Wh',
      camera: '12MP Wide + 10MP Ultra Wide',
      weight: '466g',
      dimensions: '247.6×178.5×5.9mm',
      os: 'iPadOS 16',
    },
    availability: 'in_stock',
    stockQuantity: 23,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-003',
    name: 'Apple iPad Air 5 (M1, 2022)',
    nameAr: 'أبل آيباد إير 5 (M1، 2022)',
    description:
      'Experience desktop-class performance with the M1 chip in a thin and lightweight design. The 10.9-inch Liquid Retina display with Touch ID makes this the perfect all-purpose tablet.',
    descriptionAr:
      'اختبر أداء سطح المكتب مع شريحة M1 في تصميم رفيع وخفيف الوزن. شاشة Liquid Retina بحجم 10.9 بوصة مع Touch ID تجعل هذا الجهاز اللوحي المثالي لجميع الأغراض.',
    brand: 'Apple',
    price: 4599,
    currency: 'SAR',
    images: createImages('tab-003', 'iPad Air 5 M1', 'آيباد إير 5 M1', 3),
    specifications: {
      screenSize: '10.9"',
      resolution: '2360×1640',
      processor: 'Apple M1',
      ram: '8GB',
      storage: '128GB',
      battery: '28.6Wh',
      camera: '12MP Wide',
      weight: '461g',
      dimensions: '247.6×178.5×6.1mm',
      os: 'iPadOS 15',
    },
    availability: 'in_stock',
    stockQuantity: 42,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-004',
    name: 'Apple iPad 10th Generation (2022)',
    nameAr: 'أبل آيباد الجيل العاشر (2022)',
    description:
      'The colorful iPad with a stunning 10.9-inch Liquid Retina display, A14 Bionic chip, and USB-C. Available in fun colors and perfect for everyday use, from school to work to play.',
    descriptionAr:
      'الآيباد الملون مع شاشة Liquid Retina المذهلة بحجم 10.9 بوصة وشريحة A14 Bionic ومنفذ USB-C. متاح بألوان ممتعة ومثالي للاستخدام اليومي من المدرسة إلى العمل إلى اللعب.',
    brand: 'Apple',
    price: 2699,
    currency: 'SAR',
    images: createImages('tab-004', 'iPad 10th Gen', 'آيباد الجيل العاشر', 3),
    specifications: {
      screenSize: '10.9"',
      resolution: '2360×1640',
      processor: 'Apple A14',
      ram: '4GB',
      storage: '64GB',
      battery: '28.6Wh',
      camera: '12MP Wide',
      weight: '477g',
      dimensions: '248.6×179.5×7mm',
      os: 'iPadOS 16',
    },
    availability: 'in_stock',
    stockQuantity: 67,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-005',
    name: 'Apple iPad mini 6 (A15, 2021)',
    nameAr: 'أبل آيباد ميني 6 (A15، 2021)',
    description:
      'The powerful little tablet with an 8.3-inch Liquid Retina display and A15 Bionic chip. Compact enough to hold in one hand yet powerful enough for demanding tasks.',
    descriptionAr:
      'الجهاز اللوحي الصغير القوي مع شاشة Liquid Retina بحجم 8.3 بوصة وشريحة A15 Bionic. صغير بما يكفي لحمله بيد واحدة ولكنه قوي بما يكفي للمهام الصعبة.',
    brand: 'Apple',
    price: 3199,
    currency: 'SAR',
    images: createImages('tab-005', 'iPad Mini 6', 'آيباد ميني 6', 3),
    specifications: {
      screenSize: '8.3"',
      resolution: '2266×1488',
      processor: 'Apple A15',
      ram: '4GB',
      storage: '256GB',
      battery: '19.3Wh',
      camera: '12MP Wide',
      weight: '293g',
      dimensions: '195.4×134.8×6.3mm',
      os: 'iPadOS 15',
    },
    availability: 'in_stock',
    stockQuantity: 38,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-006',
    name: 'Samsung Galaxy Tab S9 Ultra',
    nameAr: 'سامسونج جالاكسي تاب S9 ألترا',
    description:
      'The largest and most powerful Galaxy Tab with a massive 14.6-inch Dynamic AMOLED 2X display and Snapdragon 8 Gen 2 processor. Includes the S Pen and is built for ultimate productivity and entertainment.',
    descriptionAr:
      'أكبر وأقوى جالاكسي تاب مع شاشة Dynamic AMOLED 2X ضخمة بحجم 14.6 بوصة ومعالج Snapdragon 8 Gen 2. يشمل قلم S Pen ومصمم للإنتاجية والترفيه الفائقين.',
    brand: 'Samsung',
    price: 8799,
    currency: 'SAR',
    images: createImages('tab-006', 'Galaxy Tab S9 Ultra', 'جالاكسي تاب S9 ألترا', 3),
    specifications: {
      screenSize: '14.6"',
      resolution: '2960×1848',
      processor: 'Snapdragon 8 Gen 2',
      ram: '12GB',
      storage: '512GB',
      battery: '11200mAh',
      camera: '13MP + 8MP Ultra Wide',
      weight: '732g',
      dimensions: '326.4×208.6×5.5mm',
      os: 'Android 13, One UI 5',
    },
    availability: 'in_stock',
    stockQuantity: 11,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-007',
    name: 'Samsung Galaxy Tab S9+',
    nameAr: 'سامسونج جالاكسي تاب S9 بلس',
    description:
      'The large-screen flagship tablet with a 12.4-inch Dynamic AMOLED 2X display and Snapdragon 8 Gen 2. Perfect for multitasking with DeX mode and the included S Pen.',
    descriptionAr:
      'الجهاز اللوحي الرائد بشاشة كبيرة مقاس 12.4 بوصة Dynamic AMOLED 2X ومعالج Snapdragon 8 Gen 2. مثالي لتعدد المهام مع وضع DeX وقلم S Pen المرفق.',
    brand: 'Samsung',
    price: 6299,
    currency: 'SAR',
    images: createImages('tab-007', 'Galaxy Tab S9+', 'جالاكسي تاب S9 بلس', 3),
    specifications: {
      screenSize: '12.4"',
      resolution: '2800×1752',
      processor: 'Snapdragon 8 Gen 2',
      ram: '12GB',
      storage: '256GB',
      battery: '10090mAh',
      camera: '13MP + 8MP Ultra Wide',
      weight: '586g',
      dimensions: '285.4×185.4×5.7mm',
      os: 'Android 13, One UI 5',
    },
    availability: 'preorder',
    stockQuantity: 0,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-008',
    name: 'Samsung Galaxy Tab S9',
    nameAr: 'سامسونج جالاكسي تاب S9',
    description:
      'The compact flagship tablet featuring an 11-inch Dynamic AMOLED 2X display and Snapdragon 8 Gen 2. Water-resistant design with IP68 rating and S Pen included.',
    descriptionAr:
      'الجهاز اللوحي الرائد المدمج مع شاشة Dynamic AMOLED 2X بحجم 11 بوصة ومعالج Snapdragon 8 Gen 2. تصميم مقاوم للماء بتصنيف IP68 مع قلم S Pen مرفق.',
    brand: 'Samsung',
    price: 4799,
    currency: 'SAR',
    images: createImages('tab-008', 'Galaxy Tab S9', 'جالاكسي تاب S9', 3),
    specifications: {
      screenSize: '11"',
      resolution: '2560×1600',
      processor: 'Snapdragon 8 Gen 2',
      ram: '8GB',
      storage: '128GB',
      battery: '8400mAh',
      camera: '13MP',
      weight: '487g',
      dimensions: '254.3×165.8×5.9mm',
      os: 'Android 13, One UI 5',
    },
    availability: 'in_stock',
    stockQuantity: 29,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-009',
    name: 'Samsung Galaxy Tab A8',
    nameAr: 'سامسونج جالاكسي تاب A8',
    description:
      'An affordable tablet for everyday entertainment with a 10.5-inch TFT display and quad speakers. Great for streaming, browsing, and video calls with the family.',
    descriptionAr:
      'جهاز لوحي بأسعار معقولة للترفيه اليومي مع شاشة TFT بحجم 10.5 بوصة وأربعة مكبرات صوت. رائع للبث والتصفح ومكالمات الفيديو مع العائلة.',
    brand: 'Samsung',
    price: 999,
    currency: 'SAR',
    images: createImages('tab-009', 'Galaxy Tab A8', 'جالاكسي تاب A8', 2),
    specifications: {
      screenSize: '10.5"',
      resolution: '1920×1200',
      processor: 'Unisoc T618',
      ram: '4GB',
      storage: '64GB',
      battery: '7040mAh',
      camera: '8MP',
      weight: '508g',
      dimensions: '246.8×161.9×6.9mm',
      os: 'Android 11',
    },
    availability: 'in_stock',
    stockQuantity: 95,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-010',
    name: 'Samsung Galaxy Tab A7 Lite',
    nameAr: 'سامسونج جالاكسي تاب A7 لايت',
    description:
      'A compact and affordable 8.7-inch tablet perfect for kids and casual use. Lightweight design with a long-lasting battery and expandable storage.',
    descriptionAr:
      'جهاز لوحي مضغوط وبأسعار معقولة بحجم 8.7 بوصة مثالي للأطفال والاستخدام العادي. تصميم خفيف الوزن مع بطارية طويلة الأمد وتخزين قابل للتوسيع.',
    brand: 'Samsung',
    price: 599,
    currency: 'SAR',
    images: createImages('tab-010', 'Galaxy Tab A7 Lite', 'جالاكسي تاب A7 لايت', 2),
    specifications: {
      screenSize: '8.7"',
      resolution: '1340×800',
      processor: 'MediaTek MT8768',
      ram: '3GB',
      storage: '32GB',
      battery: '5100mAh',
      camera: '8MP',
      weight: '366g',
      dimensions: '212.5×124.7×8mm',
      os: 'Android 11',
    },
    availability: 'in_stock',
    stockQuantity: 120,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-011',
    name: 'Lenovo Tab P12 Pro',
    nameAr: 'لينوفو تاب P12 برو',
    description:
      'A premium Android tablet with a 12.6-inch AMOLED display and Snapdragon 8 Gen 1 processor. Comes with the Lenovo Precision Pen 3 for note-taking and drawing.',
    descriptionAr:
      'جهاز لوحي أندرويد متميز مع شاشة AMOLED بحجم 12.6 بوصة ومعالج Snapdragon 8 Gen 1. يأتي مع قلم Lenovo Precision Pen 3 للملاحظات والرسم.',
    brand: 'Lenovo',
    price: 4199,
    currency: 'SAR',
    images: createImages('tab-011', 'Lenovo Tab P12 Pro', 'لينوفو تاب P12 برو', 3),
    specifications: {
      screenSize: '12.6"',
      resolution: '2560×1600',
      processor: 'Snapdragon 8 Gen 1',
      ram: '8GB',
      storage: '256GB',
      battery: '10200mAh',
      camera: '13MP + 5MP',
      weight: '565g',
      dimensions: '285.3×184.2×5.6mm',
      os: 'Android 12',
    },
    availability: 'out_of_stock',
    stockQuantity: 0,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-012',
    name: 'Lenovo Tab P11 (2nd Gen)',
    nameAr: 'لينوفو تاب P11 (الجيل الثاني)',
    description:
      'A versatile mid-range tablet with an 11-inch 2K display and MediaTek Helio G99 processor. Ideal for entertainment, light productivity, and learning.',
    descriptionAr:
      'جهاز لوحي متوسط المدى متعدد الاستخدامات مع شاشة 2K بحجم 11 بوصة ومعالج MediaTek Helio G99. مثالي للترفيه والإنتاجية الخفيفة والتعلم.',
    brand: 'Lenovo',
    price: 1499,
    currency: 'SAR',
    images: createImages('tab-012', 'Lenovo Tab P11', 'لينوفو تاب P11', 3),
    specifications: {
      screenSize: '11"',
      resolution: '2000×1200',
      processor: 'MediaTek Helio G99',
      ram: '6GB',
      storage: '128GB',
      battery: '7700mAh',
      camera: '13MP + 8MP',
      weight: '490g',
      dimensions: '258.4×163×7.5mm',
      os: 'Android 12',
    },
    availability: 'in_stock',
    stockQuantity: 54,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-013',
    name: 'Lenovo Tab M10 Plus (3rd Gen)',
    nameAr: 'لينوفو تاب M10 بلس (الجيل الثالث)',
    description:
      'An affordable family tablet with a 10.6-inch 2K display and quad speakers tuned by Dolby Atmos. Great for streaming movies, video calls, and kids\' entertainment.',
    descriptionAr:
      'جهاز لوحي عائلي بأسعار معقولة مع شاشة 2K بحجم 10.6 بوصة وأربعة مكبرات صوت مضبوطة بتقنية Dolby Atmos. رائع لبث الأفلام ومكالمات الفيديو وترفيه الأطفال.',
    brand: 'Lenovo',
    price: 799,
    currency: 'SAR',
    images: createImages('tab-013', 'Lenovo Tab M10 Plus', 'لينوفو تاب M10 بلس', 2),
    specifications: {
      screenSize: '10.6"',
      resolution: '2000×1200',
      processor: 'MediaTek Helio G80',
      ram: '4GB',
      storage: '64GB',
      battery: '7700mAh',
      camera: '8MP',
      weight: '465g',
      dimensions: '251.2×158.8×7.5mm',
      os: 'Android 12',
    },
    availability: 'in_stock',
    stockQuantity: 78,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-014',
    name: 'Microsoft Surface Pro 9',
    nameAr: 'مايكروسوفت سيرفس برو 9',
    description:
      'The powerful 2-in-1 laptop with a 13-inch PixelSense Flow display and Intel Core i7 processor. Runs full Windows 11 and is perfect for professionals who need a laptop and tablet in one.',
    descriptionAr:
      'الكمبيوتر المحمول 2 في 1 القوي مع شاشة PixelSense Flow بحجم 13 بوصة ومعالج Intel Core i7. يعمل بنظام Windows 11 الكامل ومثالي للمحترفين الذين يحتاجون إلى كمبيوتر محمول وجهاز لوحي في جهاز واحد.',
    brand: 'Microsoft',
    price: 8199,
    currency: 'SAR',
    images: createImages('tab-014', 'Surface Pro 9', 'سيرفس برو 9', 3),
    specifications: {
      screenSize: '13"',
      resolution: '2880×1920',
      processor: 'Intel Core i7-1265U',
      ram: '16GB',
      storage: '512GB',
      battery: '47.7Wh',
      camera: '10MP + 5MP',
      weight: '879g',
      dimensions: '287×209×9.3mm',
      os: 'Windows 11',
    },
    availability: 'in_stock',
    stockQuantity: 8,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-015',
    name: 'Microsoft Surface Go 3',
    nameAr: 'مايكروسوفت سيرفس جو 3',
    description:
      'The lightest and most portable Surface with a 10.5-inch PixelSense display. Runs full Windows 11 and is perfect for on-the-go productivity, note-taking, and casual use.',
    descriptionAr:
      'أخف وأكثر أجهزة Surface قابلية للحمل مع شاشة PixelSense بحجم 10.5 بوصة. يعمل بنظام Windows 11 الكامل ومثالي للإنتاجية أثناء التنقل وتدوين الملاحظات والاستخدام العادي.',
    brand: 'Microsoft',
    price: 3499,
    currency: 'SAR',
    images: createImages('tab-015', 'Surface Go 3', 'سيرفس جو 3', 3),
    specifications: {
      screenSize: '10.5"',
      resolution: '1920×1280',
      processor: 'Intel Core i3-10100Y',
      ram: '8GB',
      storage: '128GB',
      battery: '28Wh',
      camera: '8MP + 5MP',
      weight: '544g',
      dimensions: '245×175×8.3mm',
      os: 'Windows 11',
    },
    availability: 'preorder',
    stockQuantity: 0,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-016',
    name: 'Huawei MatePad Pro 12.6',
    nameAr: 'هواوي ميت باد برو 12.6',
    description:
      'A flagship tablet with a 12.6-inch OLED display and Kirin 9000 processor. Features the M-Pencil stylus support and HarmonyOS for a seamless multi-device experience.',
    descriptionAr:
      'جهاز لوحي رائد مع شاشة OLED بحجم 12.6 بوصة ومعالج Kirin 9000. يتميز بدعم قلم M-Pencil ونظام HarmonyOS لتجربة سلسة متعددة الأجهزة.',
    brand: 'Huawei',
    price: 5499,
    currency: 'SAR',
    images: createImages('tab-016', 'MatePad Pro 12.6', 'ميت باد برو 12.6', 3),
    specifications: {
      screenSize: '12.6"',
      resolution: '2560×1600',
      processor: 'Kirin 9000',
      ram: '8GB',
      storage: '256GB',
      battery: '10050mAh',
      camera: '13MP + 8MP',
      weight: '609g',
      dimensions: '286.5×184.7×6.7mm',
      os: 'HarmonyOS 3',
    },
    availability: 'in_stock',
    stockQuantity: 18,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-017',
    name: 'Huawei MatePad 11',
    nameAr: 'هواوي ميت باد 11',
    description:
      'A versatile mid-range tablet with an 11-inch FullView display and Snapdragon 870 processor. Excellent for media consumption, note-taking, and light creative work.',
    descriptionAr:
      'جهاز لوحي متوسط المدى متعدد الاستخدامات مع شاشة FullView بحجم 11 بوصة ومعالج Snapdragon 870. ممتاز لاستهلاك الوسائط وتدوين الملاحظات والعمل الإبداعي الخفيف.',
    brand: 'Huawei',
    price: 2799,
    currency: 'SAR',
    images: createImages('tab-017', 'MatePad 11', 'ميت باد 11', 3),
    specifications: {
      screenSize: '11"',
      resolution: '2560×1600',
      processor: 'Snapdragon 870',
      ram: '6GB',
      storage: '128GB',
      battery: '7250mAh',
      camera: '13MP',
      weight: '485g',
      dimensions: '260×165.3×7.3mm',
      os: 'HarmonyOS 3',
    },
    availability: 'in_stock',
    stockQuantity: 45,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-018',
    name: 'Huawei MatePad T10',
    nameAr: 'هواوي ميت باد T10',
    description:
      'An entry-level tablet with a 9.7-inch display perfect for kids and basic tasks. Comes with Huawei Kid\'s Corner and Read&Go pre-installed for educational content.',
    descriptionAr:
      'جهاز لوحي للمبتدئين مع شاشة بحجم 9.7 بوصة مثالي للأطفال والمهام الأساسية. يأتي مع ركن الأطفال وقراءة وانطلاق مثبتة مسبقًا للمحتوى التعليمي.',
    brand: 'Huawei',
    price: 649,
    currency: 'SAR',
    images: createImages('tab-018', 'MatePad T10', 'ميت باد T10', 2),
    specifications: {
      screenSize: '9.7"',
      resolution: '1280×800',
      processor: 'Kirin 710A',
      ram: '3GB',
      storage: '32GB',
      battery: '5100mAh',
      camera: '5MP',
      weight: '450g',
      dimensions: '240.2×159×8.4mm',
      os: 'HarmonyOS 2',
    },
    availability: 'in_stock',
    stockQuantity: 110,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-019',
    name: 'Xiaomi Pad 6',
    nameAr: 'شاومي باد 6',
    description:
      'A powerful mid-range tablet with an 11-inch 144Hz LCD display and Snapdragon 870 processor. Great for gaming, streaming, and productivity with MIUI Pad features.',
    descriptionAr:
      'جهاز لوحي متوسط المدى قوي مع شاشة LCD بمعدل 144 هرتز بحجم 11 بوصة ومعالج Snapdragon 870. رائع للألعاب والبث والإنتاجية مع ميزات MIUI Pad.',
    brand: 'Xiaomi',
    price: 2299,
    currency: 'SAR',
    images: createImages('tab-019', 'Xiaomi Pad 6', 'شاومي باد 6', 3),
    specifications: {
      screenSize: '11"',
      resolution: '2880×1800',
      processor: 'Snapdragon 870',
      ram: '8GB',
      storage: '256GB',
      battery: '8840mAh',
      camera: '13MP',
      weight: '490g',
      dimensions: '254×165.2×6.5mm',
      os: 'MIUI 14 (Android 13)',
    },
    availability: 'in_stock',
    stockQuantity: 36,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-020',
    name: 'Xiaomi Pad 5',
    nameAr: 'شاومي باد 5',
    description:
      'A feature-packed tablet with an 11-inch 120Hz WQHD+ display and Snapdragon 860 processor. Supports the Xiaomi Smart Pen for note-taking and drawing.',
    descriptionAr:
      'جهاز لوحي مليء بالميزات مع شاشة WQHD+ بمعدل 120 هرتز بحجم 11 بوصة ومعالج Snapdragon 860. يدعم قلم شاومي الذكي للملاحظات والرسم.',
    brand: 'Xiaomi',
    price: 1799,
    currency: 'SAR',
    images: createImages('tab-020', 'Xiaomi Pad 5', 'شاومي باد 5', 3),
    specifications: {
      screenSize: '11"',
      resolution: '2560×1600',
      processor: 'Snapdragon 860',
      ram: '6GB',
      storage: '128GB',
      battery: '8720mAh',
      camera: '13MP',
      weight: '511g',
      dimensions: '254.7×166.3×6.9mm',
      os: 'MIUI 13 (Android 11)',
    },
    availability: 'out_of_stock',
    stockQuantity: 0,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-021',
    name: 'Xiaomi Redmi Pad SE',
    nameAr: 'شاومي ريدمي باد SE',
    description:
      'An affordable 11-inch tablet with a 90Hz adaptive display and Snapdragon 680 processor. Perfect for streaming, browsing, and light productivity on a budget.',
    descriptionAr:
      'جهاز لوحي بأسعار معقولة مقاس 11 بوصة مع شاشة متكيفة بمعدل 90 هرتز ومعالج Snapdragon 680. مثالي للبث والتصفح والإنتاجية الخفيفة بميزانية محدودة.',
    brand: 'Xiaomi',
    price: 1199,
    currency: 'SAR',
    images: createImages('tab-021', 'Redmi Pad SE', 'ريدمي باد SE', 2),
    specifications: {
      screenSize: '11"',
      resolution: '1920×1200',
      processor: 'Snapdragon 680',
      ram: '6GB',
      storage: '128GB',
      battery: '8000mAh',
      camera: '8MP',
      weight: '478g',
      dimensions: '255.5×167.2×7.4mm',
      os: 'MIUI 14 (Android 13)',
    },
    availability: 'in_stock',
    stockQuantity: 88,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-022',
    name: 'Amazon Fire HD 10 (2023)',
    nameAr: 'أمازون فاير HD 10 (2023)',
    description:
      'Amazon\'s popular 10.1-inch tablet with a 1080p Full HD display and octa-core processor. Fully integrated with Amazon services, Alexa, and the Appstore.',
    descriptionAr:
      'الجهاز اللوحي الشهير من أمازون بشاشة 10.1 بوصة Full HD عالية الدقة ومعالج ثماني النواة. متكامل بالكامل مع خدمات أمازون وأليكسا ومتجر التطبيقات.',
    brand: 'Amazon',
    price: 1299,
    currency: 'SAR',
    images: createImages('tab-022', 'Fire HD 10', 'فاير HD 10', 2),
    specifications: {
      screenSize: '10.1"',
      resolution: '1920×1200',
      processor: 'Octa-core 2.0GHz',
      ram: '3GB',
      storage: '64GB',
      battery: '6500mAh',
      camera: '5MP',
      weight: '468g',
      dimensions: '247×166×8.7mm',
      os: 'Fire OS 8',
    },
    availability: 'in_stock',
    stockQuantity: 63,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-023',
    name: 'Amazon Fire HD 8 (2022)',
    nameAr: 'أمازون فاير HD 8 (2022)',
    description:
      'A compact and affordable 8-inch tablet perfect for reading, streaming, and staying connected with Alexa. Lightweight design with a long battery life.',
    descriptionAr:
      'جهاز لوحي مضغوط وبأسعار معقولة بحجم 8 بوصات مثالي للقراءة والبث والبقاء على اتصال مع أليكسا. تصميم خفيف الوزن مع عمر بطارية طويل.',
    brand: 'Amazon',
    price: 849,
    currency: 'SAR',
    images: createImages('tab-023', 'Fire HD 8', 'فاير HD 8', 2),
    specifications: {
      screenSize: '8"',
      resolution: '1280×800',
      processor: 'Hexa-core 2.0GHz',
      ram: '2GB',
      storage: '32GB',
      battery: '4850mAh',
      camera: '5MP',
      weight: '337g',
      dimensions: '202×137×9.7mm',
      os: 'Fire OS 8',
    },
    availability: 'in_stock',
    stockQuantity: 132,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-024',
    name: 'Apple iPad Pro 12.9-inch (M1, 2021)',
    nameAr: 'أبل آيباد برو 12.9 بوصة (M1، 2021)',
    description:
      'The previous generation iPad Pro with the M1 chip featuring a 12.9-inch Liquid Retina XDR display. Still incredibly powerful and available at a great price.',
    descriptionAr:
      'الجيل السابق من آيباد برو مع شريحة M1 وشاشة Liquid Retina XDR بحجم 12.9 بوصة. لا يزال قويًا بشكل لا يصدق ومتوفر بسعر رائع.',
    brand: 'Apple',
    price: 6499,
    currency: 'SAR',
    images: createImages('tab-024', 'iPad Pro 12.9 M1', 'آيباد برو 12.9 M1', 3),
    specifications: {
      screenSize: '12.9"',
      resolution: '2732×2048',
      processor: 'Apple M1',
      ram: '16GB',
      storage: '1TB',
      battery: '40.88Wh',
      camera: '12MP Wide + 10MP Ultra Wide',
      weight: '682g',
      dimensions: '280.6×214.9×6.4mm',
      os: 'iPadOS 14',
    },
    availability: 'in_stock',
    stockQuantity: 5,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-025',
    name: 'Samsung Galaxy Tab S9 FE',
    nameAr: 'سامسونج جالاكسي تاب S9 FE',
    description:
      'The Fan Edition of the Galaxy Tab S9 series with a 10.9-inch display and Exynos 2200 processor. Includes the S Pen and offers core flagship features at a lower price.',
    descriptionAr:
      'نسخة المعجبين من سلسلة جالاكسي تاب S9 مع شاشة بحجم 10.9 بوصة ومعالج Exynos 2200. يشمل قلم S Pen ويقدم ميزات الرائد الأساسية بسعر أقل.',
    brand: 'Samsung',
    price: 2999,
    currency: 'SAR',
    images: createImages('tab-025', 'Galaxy Tab S9 FE', 'جالاكسي تاب S9 FE', 3),
    specifications: {
      screenSize: '10.9"',
      resolution: '2304×1440',
      processor: 'Exynos 2200',
      ram: '6GB',
      storage: '128GB',
      battery: '8000mAh',
      camera: '8MP',
      weight: '523g',
      dimensions: '254.3×165.8×6.5mm',
      os: 'Android 13, One UI 5',
    },
    availability: 'preorder',
    stockQuantity: 0,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-026',
    name: 'Lenovo Tab M8 (HD)',
    nameAr: 'لينوفو تاب M8 (إتش دي)',
    description:
      'A compact 8-inch tablet with a metal body and HD display. Designed for entertainment on the go with a lightweight build and long-lasting battery.',
    descriptionAr:
      'جهاز لوحي مضغوط بحجم 8 بوصات مع هيكل معدني وشاشة عالية الدقة. مصمم للترفيه أثناء التنقل مع هيكل خفيف الوزن وبطارية طويلة الأمد.',
    brand: 'Lenovo',
    price: 549,
    currency: 'SAR',
    images: createImages('tab-026', 'Lenovo Tab M8', 'لينوفو تاب M8', 2),
    specifications: {
      screenSize: '8"',
      resolution: '1280×720',
      processor: 'MediaTek Helio A22',
      ram: '3GB',
      storage: '32GB',
      battery: '5000mAh',
      camera: '5MP',
      weight: '305g',
      dimensions: '199.9×121.8×9.2mm',
      os: 'Android 9',
    },
    availability: 'in_stock',
    stockQuantity: 156,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'tab-027',
    name: 'Huawei MatePad Paper',
    nameAr: 'هواوي ميت باد بيبر',
    description:
      'A unique 10.3-inch e-ink tablet designed for reading and note-taking. Features a matte e-ink display with a natural paper-like writing experience.',
    descriptionAr:
      'جهاز لوحي فريد من نوعه بحجم 10.3 بوصة بشاشة حبر إلكتروني مصمم للقراءة وتدوين الملاحظات. يتميز بشاشة حبر إلكتروني غير لامعة مع تجربة كتابة طبيعية تشبه الورق.',
    brand: 'Huawei',
    price: 3199,
    currency: 'SAR',
    images: createImages('tab-027', 'MatePad Paper', 'ميت باد بيبر', 2),
    specifications: {
      screenSize: '10.3"',
      resolution: '1872×1404',
      processor: 'Kirin 820E',
      ram: '4GB',
      storage: '64GB',
      battery: '3625mAh',
      camera: '–',
      weight: '360g',
      dimensions: '225.2×182.7×6.7mm',
      os: 'HarmonyOS 2',
    },
    availability: 'out_of_stock',
    stockQuantity: 0,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
];

export const mockCountries: Country[] = [
  { code: 'SA', name: 'Saudi Arabia', nameAr: 'المملكة العربية السعودية', currency: 'SAR', shippingZone: 'gcc' },
  { code: 'AE', name: 'United Arab Emirates', nameAr: 'الإمارات العربية المتحدة', currency: 'AED', shippingZone: 'gcc' },
  { code: 'KW', name: 'Kuwait', nameAr: 'الكويت', currency: 'KWD', shippingZone: 'gcc' },
  { code: 'QA', name: 'Qatar', nameAr: 'قطر', currency: 'QAR', shippingZone: 'gcc' },
  { code: 'BH', name: 'Bahrain', nameAr: 'البحرين', currency: 'BHD', shippingZone: 'gcc' },
  { code: 'OM', name: 'Oman', nameAr: 'عمان', currency: 'OMR', shippingZone: 'gcc' },
  { code: 'EG', name: 'Egypt', nameAr: 'مصر', currency: 'EGP', shippingZone: 'north_africa' },
  { code: 'JO', name: 'Jordan', nameAr: 'الأردن', currency: 'JOD', shippingZone: 'levant' },
  { code: 'MA', name: 'Morocco', nameAr: 'المغرب', currency: 'MAD', shippingZone: 'north_africa' },
  { code: 'DZ', name: 'Algeria', nameAr: 'الجزائر', currency: 'DZD', shippingZone: 'north_africa' },
];

export const mockShippingOptions: ShippingOption[] = [
  { id: 'standard-sa', name: 'Standard Shipping', nameAr: 'شحن قياسي', cost: 29, currency: 'SAR', estimatedDays: 5, countryCode: 'SA' },
  { id: 'express-sa', name: 'Express Shipping', nameAr: 'شحن سريع', cost: 59, currency: 'SAR', estimatedDays: 2, countryCode: 'SA' },
  { id: 'standard-ae', name: 'Standard Shipping', nameAr: 'شحن قياسي', cost: 25, currency: 'AED', estimatedDays: 5, countryCode: 'AE' },
  { id: 'express-ae', name: 'Express Shipping', nameAr: 'شحن سريع', cost: 55, currency: 'AED', estimatedDays: 2, countryCode: 'AE' },
  { id: 'standard-kw', name: 'Standard Shipping', nameAr: 'شحن قياسي', cost: 3, currency: 'KWD', estimatedDays: 5, countryCode: 'KW' },
  { id: 'express-kw', name: 'Express Shipping', nameAr: 'شحن سريع', cost: 7, currency: 'KWD', estimatedDays: 2, countryCode: 'KW' },
  { id: 'standard-qa', name: 'Standard Shipping', nameAr: 'شحن قياسي', cost: 35, currency: 'QAR', estimatedDays: 5, countryCode: 'QA' },
  { id: 'express-qa', name: 'Express Shipping', nameAr: 'شحن سريع', cost: 75, currency: 'QAR', estimatedDays: 2, countryCode: 'QA' },
  { id: 'standard-bh', name: 'Standard Shipping', nameAr: 'شحن قياسي', cost: 3, currency: 'BHD', estimatedDays: 5, countryCode: 'BH' },
  { id: 'express-bh', name: 'Express Shipping', nameAr: 'شحن سريع', cost: 7, currency: 'BHD', estimatedDays: 2, countryCode: 'BH' },
  { id: 'standard-om', name: 'Standard Shipping', nameAr: 'شحن قياسي', cost: 3, currency: 'OMR', estimatedDays: 5, countryCode: 'OM' },
  { id: 'express-om', name: 'Express Shipping', nameAr: 'شحن سريع', cost: 7, currency: 'OMR', estimatedDays: 2, countryCode: 'OM' },
  { id: 'standard-eg', name: 'Standard Shipping', nameAr: 'شحن قياسي', cost: 120, currency: 'EGP', estimatedDays: 7, countryCode: 'EG' },
  { id: 'express-eg', name: 'Express Shipping', nameAr: 'شحن سريع', cost: 250, currency: 'EGP', estimatedDays: 3, countryCode: 'EG' },
  { id: 'standard-jo', name: 'Standard Shipping', nameAr: 'شحن قياسي', cost: 5, currency: 'JOD', estimatedDays: 7, countryCode: 'JO' },
  { id: 'express-jo', name: 'Express Shipping', nameAr: 'شحن سريع', cost: 10, currency: 'JOD', estimatedDays: 3, countryCode: 'JO' },
  { id: 'standard-ma', name: 'Standard Shipping', nameAr: 'شحن قياسي', cost: 80, currency: 'MAD', estimatedDays: 7, countryCode: 'MA' },
  { id: 'express-ma', name: 'Express Shipping', nameAr: 'شحن سريع', cost: 180, currency: 'MAD', estimatedDays: 3, countryCode: 'MA' },
  { id: 'standard-dz', name: 'Standard Shipping', nameAr: 'شحن قياسي', cost: 800, currency: 'DZD', estimatedDays: 7, countryCode: 'DZ' },
  { id: 'express-dz', name: 'Express Shipping', nameAr: 'شحن سريع', cost: 1800, currency: 'DZD', estimatedDays: 3, countryCode: 'DZ' },
];
